version: '2.4'
services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      - elasticsearch
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - elasticsearch
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9103,EXTERNAL://:9092,INTERNAL://:19092,
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-server:9103,EXTERNAL://localhost:9092,,INTERNAL://kafka-server:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper-server

  nglp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nglp-analytics
    networks:
      - elasticsearch
    ports:
      - '8000:8000'
    depends_on:
      - kafka-server

  nglp-events-consumer:
    build:
      context: .
      dockerfile: Dockerfile-events-consumer
    container_name: nglp-events-consumer
    networks:
      - elasticsearch
    depends_on:
      - nglp

networks:
  elasticsearch:
    driver: bridge
